"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Lang = "es" | "en";

type Dictionary = typeof dictionaries.es;

const dictionaries = {
  es: {
    nav: { signIn: "Iniciar Sesión", chat: "Abrir chat", language: "English" },
    hero: {
      title: "La inteligencia artificial para Latinoamérica.",
      highlight: "Latinoamérica",
      body: "Una forma más simple y accesible de obtener respuestas, aprender, crear contenido y ser más productivo. Disponible en español e inglés, en cualquier momento.",
      primary: "Comenzar gratis",
      secondary: "Ver demo",
      availability: "Agentes de IA Plus y Pro también disponibles",
      downloadApp: "Descarga nuestra app en tu teléfono",
    },
    pricing: {
      title: "Simple, flexible y transparente",
      body: "Empieza gratis y obtén acceso a más potencia cuando la necesites. Sin tarjetas obligatorias, sin contratos y con la libertad de cancelar cuando quieras.",
      popular: "Más popular",
      ctaFree: "Comenzar gratis",
      ctaPlus: "Obtener Plus",
      ctaPro: "Obtener Pro",
      freeName: "Gratis",
      plusName: "Plus",
      proName: "Pro",
      freeDesc: "Empieza gratis y descubre todo lo que Nopal puede hacer por ti. Sin tarjeta de crédito.",
      plusDesc: "Mayor velocidad, más mensajes y una experiencia mejorada para estudiar, trabajar y crear.",
      proDesc: "La mejor experiencia de Nopal para proyectos, trabajo y uso intensivo.",
      freeFeatures: ["Límite de 20 mensajes al día", "Acceso al chat", "Historial de conversaciones", "Sin tarjeta de crédito"],
      plusFeatures: ["Mensajes ilimitados", "Sin anuncios", "Respuestas más rápidas", "Historial de conversaciones"],
      proFeatures: ["Uso ampliado", "Modelos premium", "Acceso prioritario", "Soporte preferente"],
      perMonth: "MXN / mes",
      comparison: "Comparativa",
      unlimited: "Ilimitados",
      unlimitedStar: "Ilimitados*",
      rows: ["Mensajes por día", "Historial de conversaciones", "Sin anuncios", "Respuestas más rápidas", "Modelos premium", "Soporte preferente"],
      fairUse: "Uso justo: Precios en la moneda de su país. Puede cancelar en cualquier momento.",
    },
    faq: {
      title: "Preguntas frecuentes",
      items: [
        ["¿Qué es NopalAI?", "La inteligencia artificial para Latinoamérica.\n\nNopal te ayuda a obtener respuestas, aprender, traducir, crear contenido y ser más productivo, todo desde una sola plataforma.\n\nSimple, rápido y accesible, está diseñado para acompañarte en tus estudios, trabajo y proyectos, con una experiencia pensada para las necesidades de Latinoamérica."],
        ["¿Es gratis?", "Empieza gratis y descubre todo lo que Nopal puede hacer por ti. Sin tarjeta de crédito.\n\nCuando necesites más, desbloquea Plus o Pro para obtener mayor velocidad, más capacidad y una experiencia diseñada para quienes usan la inteligencia artificial todos los días.\n\nPotente, simple y accesible. Pensado para Latinoamérica."],
        ["¿Puedo cancelar cuando quiera?", "Sí. Puedes cancelar en cualquier momento.\n\nTu suscripción seguirá activa hasta el final del periodo ya pagado. Sin contratos, sin cargos ocultos y con total libertad para volver cuando quieras."],
        ["¿Necesito una tarjeta de crédito para empezar?", "No. Puedes comenzar a usar Nopal gratis sin necesidad de ingresar una tarjeta de crédito. Regístrate y empieza a conversar en segundos."],
        ["¿Cuál es la diferencia entre Gratis, Plus y Pro?", "El plan Gratis es ideal para comenzar y descubrir todo lo que Nopal puede hacer por ti. Plus ofrece una experiencia más rápida y mayor capacidad para quienes usan la inteligencia artificial todos los días. Pro está diseñado para usuarios que necesitan el máximo rendimiento para trabajo, estudio y proyectos más exigentes."],
        ["¿Mis conversaciones son privadas?", "Sí. La privacidad y seguridad de tus datos son importantes para nosotros. Tus conversaciones se manejan de forma segura para ofrecerte la mejor experiencia posible."],
        ["¿Puedo usar Nopal desde mi celular?", "Sí. Nopal funciona perfectamente en teléfonos, tabletas y computadoras, para que puedas acceder a tus conversaciones y herramientas desde cualquier lugar."],
        ["¿Qué métodos de pago aceptan?", "Aceptamos múltiples métodos de pago para que puedas elegir el que mejor se adapte a ti. Puedes pagar con tarjetas de crédito y débito, PayPal, Mercado Pago, OXXO y otras opciones disponibles en tu región. Todas las transacciones son seguras y puedes administrar o cancelar tu suscripción en cualquier momento."],
        ["¿Habrá nuevas funciones en el futuro?", "Sí. Estamos mejorando Nopal constantemente y trabajamos en nuevas funciones y herramientas para ayudarte a estudiar, trabajar, crear contenido y ser más productivo cada día."],
      ],
    },
    cta: { title: "Prueba la inteligencia artificial para Latinoamérica", body: "Gratis para siempre. Sin tarjeta. Empieza en segundos.", prices: "Ver planes" },
    footer: { privacy: "Privacidad", terms: "Términos", made: "Hecho para LATAM" },
    dash: {
      openMenu: "Abrir menú",
      newChat: "Nuevo chat",
      home: "Inicio",
      recents: "Recientes",
      emptyChats: "Tus conversaciones aparecerán aquí.",
      chatOptions: "Opciones del chat",
      rename: "Renombrar",
      delete: "Eliminar",
      upgrade: "Mejorar plan",
      account: "Mi cuenta",
      collapse: "Contraer barra lateral",
      pin: "Fijar barra lateral",
      renameTitle: "Renombrar chat",
      chatNamePlaceholder: "Nombre del chat",
      cancel: "Cancelar",
      save: "Guardar",
      deleteTitle: "¿Eliminar este chat?",
      deleteBodyPre: "Se eliminará “",
      deleteBodyPost: "” y todos sus mensajes. Esta acción no se puede deshacer.",
      disclaimer: "NopalAI puede cometer errores. Verifica la información importante.",
      stop: "Detener",
      send: "Enviar",
      askPrefix: "Pregúntale a",
      emptyHeading: "¿En qué te ayudo hoy?",
      emptySub: "Elige un asistente y empieza a escribir.",
      tryWith: "Prueba con",
      assistantType: "Tipo de asistente",
      activeSuffix: "activo",
      unlimitedDesc: "Mensajes ilimitados y respuestas más rápidas.",
      todayUsage: "Uso de hoy",
      improve: "Mejorar",
      adLabel: "Publicidad",
      adAria: "Espacio publicitario",
      removeAds: "Quita los anuncios con Pro",
      copy: "Copiar",
      copied: "Copiado",
      copyAria: "Copiar respuesta",
      limitTitle: "Llegaste a tu límite de hoy",
      chooseTitle: "Elige tu mejora",
      limitDesc: "Usaste tus mensajes gratuitos de hoy. Elige Plus o Pro para seguir sin interrupciones.",
      chooseDesc: "Selecciona el plan que mejor se adapte a tu ritmo de trabajo.",
      perMonth: "MXN / mes",
      secureNote: "Cancela cuando quieras · Pago seguro con Stripe",
      upgraded: "¡Listo! 🎉 Tu plan está activo. Disfruta sin límites.",
      errSend: "No se pudo generar la respuesta. Intenta de nuevo.",
      errCreate: "No se pudo crear el chat.",
      errOpen: "No se pudo abrir el chat.",
      errRename: "No se pudo renombrar.",
      errDelete: "No se pudo eliminar.",
      errCheckout: "No se pudo iniciar el pago",
      errGeneric: "Algo salió mal. Intenta de nuevo.",
      modes: {
        general: { name: "General", suggestions: ["Escríbeme un mensaje de WhatsApp para felicitar a un cliente", "Ayúdame a redactar un correo formal para pedir una cotización", "Dame ideas para organizar mejor mi semana", "Resúmeme este texto en 3 puntos clave"] },
        translation: { name: "Traducción", suggestions: ["Traduce 'la cuenta, por favor' al inglés para un turista", "Traduce este correo al inglés de forma formal", "¿Cómo se dice 'estoy en la chamba' en inglés natural?", "Tradúceme este mensaje del inglés al español"] },
        school: { name: "Escuela", suggestions: ["Explícame el teorema de Pitágoras con un ejemplo sencillo", "Ayúdame a hacer un resumen de la Revolución Mexicana", "¿Cómo resuelvo una ecuación de segundo grado?", "Corrige y mejora mi ensayo"] },
        content: { name: "Contenido", suggestions: ["Dame 5 ideas de contenido para Instagram esta semana", "Escribe un guion para un Reel de TikTok de 30 segundos", "Crea captions con hashtags para mi negocio", "Hazme un calendario de contenido para 7 días"] },
      },
    },
  },
  en: {
    nav: { signIn: "Sign in", chat: "Open chat", language: "Español" },
    hero: {
      title: "Artificial intelligence for Latin America.",
      highlight: "Latin America",
      body: "A simpler, more accessible way to get answers, learn, create content, and be more productive. Available in Spanish and English, anytime.",
      primary: "Start free",
      secondary: "View demo",
      availability: "Plus and Pro AI agents also available",
      downloadApp: "Download our app on your phone",
    },
    pricing: {
      title: "Simple, flexible, and transparent",
      body: "Start free and unlock more power whenever you need it. No card required, no contracts, and the freedom to cancel anytime.",
      popular: "Most popular",
      ctaFree: "Start free",
      ctaPlus: "Get Plus",
      ctaPro: "Get Pro",
      freeName: "Free",
      plusName: "Plus",
      proName: "Pro",
      freeDesc: "Start free and discover everything Nopal can do for you. No credit card required.",
      plusDesc: "More speed, more messages, and an enhanced experience to study, work, and create.",
      proDesc: "The best Nopal experience for projects, work, and intensive use.",
      freeFeatures: ["20 messages per day", "Chat access", "Chat history", "No credit card"],
      plusFeatures: ["Unlimited messages", "No ads", "Faster responses", "Chat history"],
      proFeatures: ["Extended usage", "Premium models", "Priority access", "Priority support"],
      perMonth: "MXN / month",
      comparison: "Comparison",
      unlimited: "Unlimited",
      unlimitedStar: "Unlimited*",
      rows: ["Messages per day", "Chat history", "No ads", "Faster responses", "Premium models", "Priority support"],
      fairUse: "Fair use: Prices in your country's currency. You can cancel at any time.",
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        ["What is NopalAI?", "Artificial intelligence for Latin America.\n\nNopal helps you get answers, learn, translate, create content, and be more productive — all from a single platform.\n\nSimple, fast, and accessible, it's designed to support you in your studies, work, and projects, with an experience built for the needs of Latin America."],
        ["Is it free?", "Start free and discover everything Nopal can do for you. No credit card required.\n\nWhen you need more, unlock Plus or Pro for more speed, more capacity, and an experience designed for those who use artificial intelligence every day.\n\nPowerful, simple, and accessible. Built for Latin America."],
        ["Can I cancel anytime?", "Yes. You can cancel anytime.\n\nYour subscription stays active until the end of the period you've already paid for. No contracts, no hidden charges, and the freedom to come back whenever you want."],
        ["Do I need a credit card to get started?", "No. You can start using Nopal for free without entering a credit card. Sign up and start chatting in seconds."],
        ["What's the difference between Free, Plus, and Pro?", "The Free plan is perfect for getting started and discovering everything Nopal can do for you. Plus offers a faster experience and more capacity for those who use artificial intelligence every day. Pro is designed for users who need maximum performance for work, study, and more demanding projects."],
        ["Are my conversations private?", "Yes. The privacy and security of your data matter to us. Your conversations are handled securely to give you the best possible experience."],
        ["Can I use Nopal on my phone?", "Yes. Nopal works perfectly on phones, tablets, and computers, so you can access your conversations and tools from anywhere."],
        ["What payment methods do you accept?", "We accept multiple payment methods so you can choose the one that suits you best. You can pay with credit and debit cards, PayPal, Mercado Pago, OXXO, and other options available in your region. All transactions are secure, and you can manage or cancel your subscription anytime."],
        ["Will there be new features in the future?", "Yes. We're constantly improving Nopal and working on new features and tools to help you study, work, create content, and be more productive every day."],
      ],
    },
    cta: { title: "Try artificial intelligence for Latin America", body: "Free forever. No card. Start in seconds.", prices: "View plans" },
    footer: { privacy: "Privacy", terms: "Terms", made: "Made for LATAM" },
    dash: {
      openMenu: "Open menu",
      newChat: "New chat",
      home: "Home",
      recents: "Recent",
      emptyChats: "Your conversations will appear here.",
      chatOptions: "Chat options",
      rename: "Rename",
      delete: "Delete",
      upgrade: "Upgrade plan",
      account: "My account",
      collapse: "Collapse sidebar",
      pin: "Pin sidebar",
      renameTitle: "Rename chat",
      chatNamePlaceholder: "Chat name",
      cancel: "Cancel",
      save: "Save",
      deleteTitle: "Delete this chat?",
      deleteBodyPre: "“",
      deleteBodyPost: "” and all of its messages will be deleted. This can't be undone.",
      disclaimer: "NopalAI can make mistakes. Check important information.",
      stop: "Stop",
      send: "Send",
      askPrefix: "Ask",
      emptyHeading: "How can I help you today?",
      emptySub: "Pick an assistant and start typing.",
      tryWith: "Try",
      assistantType: "Assistant type",
      activeSuffix: "active",
      unlimitedDesc: "Unlimited messages and faster responses.",
      todayUsage: "Today's usage",
      improve: "Upgrade",
      adLabel: "Advertisement",
      adAria: "Advertising space",
      removeAds: "Remove ads with Pro",
      copy: "Copy",
      copied: "Copied",
      copyAria: "Copy response",
      limitTitle: "You've reached today's limit",
      chooseTitle: "Choose your upgrade",
      limitDesc: "You've used today's free messages. Choose Plus or Pro to keep going without interruptions.",
      chooseDesc: "Pick the plan that best fits your workflow.",
      perMonth: "MXN / month",
      secureNote: "Cancel anytime · Secure payment with Stripe",
      upgraded: "You're all set! 🎉 Your plan is active. Enjoy without limits.",
      errSend: "Couldn't generate a response. Please try again.",
      errCreate: "Couldn't create the chat.",
      errOpen: "Couldn't open the chat.",
      errRename: "Couldn't rename.",
      errDelete: "Couldn't delete.",
      errCheckout: "Couldn't start checkout",
      errGeneric: "Something went wrong. Please try again.",
      modes: {
        general: { name: "General", suggestions: ["Write me a WhatsApp message to congratulate a client", "Help me draft a formal email to request a quote", "Give me ideas to organize my week better", "Summarize this text into 3 key points"] },
        translation: { name: "Translation", suggestions: ["Translate 'la cuenta, por favor' to English for a tourist", "Translate this email to English formally", "How do you say 'estoy en la chamba' in natural English?", "Translate this message from English to Spanish"] },
        school: { name: "School", suggestions: ["Explain the Pythagorean theorem with a simple example", "Help me write a summary of the Mexican Revolution", "How do I solve a quadratic equation?", "Correct and improve my essay"] },
        content: { name: "Content", suggestions: ["Give me 5 content ideas for Instagram this week", "Write a 30-second TikTok Reel script", "Create captions with hashtags for my business", "Make me a 7-day content calendar"] },
      },
    },
  },
};

const LanguageContext = createContext<{ lang: Lang; setLang: (lang: Lang) => void; t: Dictionary } | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("es");

  useEffect(() => {
    const saved = window.localStorage.getItem("nopalai-lang");
    if (saved === "en" || saved === "es") setLangState(saved);
  }, []);

  const setLang = (next: Lang) => {
    setLangState(next);
    window.localStorage.setItem("nopalai-lang", next);
    document.documentElement.lang = next === "es" ? "es-MX" : "en";
  };

  const value = useMemo(() => ({ lang, setLang, t: dictionaries[lang] }), [lang]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
